[package]
name = "my_glium_util"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
glium = "0.36.0"
my_rust_matrix_lib = { version = "0.1.0", git = "https://github.com/CorentinVaillant/my_rust_matrix_lib.git" }
num = "0.4.3"
